### ISSUE TITLE
JSON-RPC

### ISSUE THREAD

**Issue by heikoheiko** [ethereum/pyethereum#180]
https://github.com/ethereum/wiki/wiki/Generic-JSON-RPC

can used to in combination w/ 
https://github.com/ethereum/wiki/wiki/JavaScript-API

to run dapps in the browser.

**Comment by heikoheiko** [comment]
json description of methods and their params:
https://github.com/ethereum/cpp-ethereum/blob/develop/libweb3jsonrpc/spec.json

**Comment by konradkonrad** [comment]
jsonrpc is part of https://github.com/ethereum/pyethapp
