### ISSUE TITLE
Support PyPy

### ISSUE THREAD

**Issue by heikoheiko** [ethereum/pyethereum#188]

**Comment by heikoheiko** [comment]
PyPy2:
-    pysha3 : not working
-    leveldb : ok
-    gevent: ok
-    repoze.lru: ok
-   pyethash: ok

test_state.py can be run with pypy (if patched to use a python keccak implementation)

**Comment by czepluch** [comment]
pysha3 working by using pycryptodome instead which also supports pypy
PR: https://github.com/ethereum/pyethereum/pull/295

**Comment by ofek** [comment]
As of #777 our secp256k1 dep supports PyPy and ships a compiled wheel for PyPy3.5-5.8
