### ISSUE TITLE
How to link peers from peers.json with each other  ?

### ISSUE THREAD

**Issue by hackappcom** [ethereum/pyethereum#198]
Hi,  I use stable version.
I've locally setup small 10 peers network (each node have separate folder, config, db and port) , and provided peers.json file:
[["127.0.0.1","30301"],["127.0.0.1","30302"],["127.0.0.1","30303"],["127.0.0.1","30304"],["127.0.0.1","30305"],["127.0.0.1","30306"],["127.0.0.1","30307"],["127.0.0.1","30308"],["127.0.0.1","30309"],["127.0.0.1","30310"] ]

But when I start nodes, I see this list only as http://127.0.0.1:30203/peers/known and http://127.0.0.1:30203/peers/connected is empty.
Also, as I see from logs, each peer started to mine it's one chain separately.

How to link peers with each other and mine common chain?

**Comment by heikoheiko** [comment]
try do use a central bootstrapping node and let the peers connect to it. 
# bootstrapping node:
pyeth -l 30300 -d data0/

# other nodes
pyeth -r 127.0.0.1 -p 30300 -l 30301 -d data1/
pyeth -r 127.0.0.1 -p 30300 -l 30302 -d data2/
pyeth -r 127.0.0.1 -p 30300 -l 30303 -d data3/
...

**Comment by hackappcom** [comment]
and  other peers bootstrap node will share peer with each other?

**Comment by heikoheiko** [comment]
yes, they all connect to the boot strap node, and then ask frequently for other peers. bootstrap node returns all known (i.e. connected) peers.

**Comment by hackappcom** [comment]
Thank you, I've just launched 10 nodes, with one minig (which was master with id 0) and everything was working as expeted, new blocks were mining, chain was synching, but then I've launched transcation generator:


while [ 1 ]; 
do 
pyethclient quicktx b8a1e70b90b28cde1ef7402bc280c5b5a357b499 1 '' 80d6c6da7450f8d84cea853286c00c6458cb7d0d037d63f59da64d264d7bc529 -H 127.0.0.1 -p 30202; 
done

and after few successfull transactions it started to slowdown. After few blocks chain stops to grow and propofate new block, here is hang state:

node_id, block_number, last_block_hash
9 23 c7c6bdcfc9efb2ca868f9932e0ed7522725622e2ade18432fac5bce6b8aa9d19
8 23 c7c6bdcfc9efb2ca868f9932e0ed7522725622e2ade18432fac5bce6b8aa9d19
7 23 c7c6bdcfc9efb2ca868f9932e0ed7522725622e2ade18432fac5bce6b8aa9d19
6 23 c7c6bdcfc9efb2ca868f9932e0ed7522725622e2ade18432fac5bce6b8aa9d19
5 23 c7c6bdcfc9efb2ca868f9932e0ed7522725622e2ade18432fac5bce6b8aa9d19
4 23 c7c6bdcfc9efb2ca868f9932e0ed7522725622e2ade18432fac5bce6b8aa9d19
3 23 c7c6bdcfc9efb2ca868f9932e0ed7522725622e2ade18432fac5bce6b8aa9d19
2 23 c7c6bdcfc9efb2ca868f9932e0ed7522725622e2ade18432fac5bce6b8aa9d19
1 23 c7c6bdcfc9efb2ca868f9932e0ed7522725622e2ade18432fac5bce6b8aa9d19
0 28 3201d9d6bbe9b2a527cd713b58459fa6485bead493232d92bf4f611616008c4e


and on master  node logs I see many lines of this kind : 

....
Thread-708:chainmanager: remote_transactions_received: [<Transaction(ab59)>, <Transaction(8cd8)>, <Transaction(35f4)>, <Transaction(4579)>, <Transaction(99be)>, <Transaction(8354)>, <Transaction(2f91)>, <Transaction(e6c0)>, <Transaction(bd18)>, <Transaction(0275)>, <Transaction(0941)>, <Transaction(5166)>, <Transaction(f5fa)>, <Transaction(cb4e)>, <Transaction(6626)>, <Transaction(4d27)>, <Transaction(ba46)>, <Transaction(1579)>, <Transaction(6a5e)>, <Transaction(82f8)>, <Transaction(ae76)>, <Transaction(a9b4)>, <Transaction(3cdf)>, <Transaction(c7cd)>, <Transaction(680c)>, <Transaction(55ff)>, <Transaction(1bb0)>, <Transaction(a077)>, <Transaction(f9f2)>, <Transaction(b617)>, <Transaction(6e3a)>, <Transaction(40f2)>, <Transaction(68fa)>, <Transaction(5de0)>, <Transaction(c093)>, <Transaction(69af)>, <Transaction(844a)>, <Transaction(0aa4)>, <Transaction(1cb7)>, <Transaction(5c37)>, <Transaction(0ca4)>, <Transaction(3542)>]
Thread-669:chainmanager: add transaction <Transaction(4d27)>
Thread-708:chainmanager: add transaction <Transaction(ab59)>
Thread-829:chainmanager: get_transactions called
Thread-715:chainmanager: add transaction <Transaction(6626)>
.....

What could be wrong here and were to start  debug it ?

**Comment by heikoheiko** [comment]
what happens if you add a `sleep 1` in the while loop
