### ISSUE TITLE
New version of structlog dependency breaks everything

### ISSUE THREAD

**Issue by ChrisCalderon** [ethereum/pyethereum#202]
reverting to version 0.4.2 fixes it. Just run `sudo pip install structlog==0.4.2` to get it working. This should be specified in the requirements.txt file.

**Comment by heikoheiko** [comment]
thank you

compatibility was already restored in the development branch 1dc44fe0e0ef8afc92dbd24eb4aa49cdd4a86f68

added your fix to the master branch.

**Comment by hynek** [comment]
Would you mind elaborating what 15.0 broke for you? Did the stdlib improvements clash with your own stuff?

**Comment by heikoheiko** [comment]
I added a new loglevel trace and didn't find a way to do so without manipulating structlog.stdlib._NAME_TO_LEVEL (name changed with v15).

https://github.com/ethereum/pyethereum/blob/1dc44fe0e0ef8afc92dbd24eb4aa49cdd4a86f68/pyethereum/slogging.py#L72
and
https://github.com/ethereum/pyethereum/blob/1dc44fe0e0ef8afc92dbd24eb4aa49cdd4a86f68/pyethereum/slogging.py#L76

**Comment by hynek** [comment]
Well, `_NAME_TO_LEVEL` has a underscore prefix for a reason. :)

What exactly do you want to achieve?  Might there a more preferable (and clean :)) way than using the internals (that are a verbatim copy from the stdlib anyways)?

**Comment by heikoheiko** [comment]
right, but i didn't see a way to add an additional log level. any hints how to implement this properly?

**Comment by hynek** [comment]
no, I’m not a fan of log levels anyways.  would you mind opening an issue on structlog stating the actual problem you’re trying to solve?  maybe we’ll find a better way and I can pull in people who know more about such things than I do.

thanks (hopefully) in advance!
