### ISSUE TITLE
AssertionError on lastest develop on Mac OS X (Yosemite)

### ISSUE THREAD

**Issue by scottzer0** [ethereum/pyethereum#203]
Traceback (most recent call last):
  File "/usr/local/bin/pyeth", line 9, in <module>
    load_entry_point('pyethereum==0.7.51-35-g2e3fc6d', 'console_scripts', 'pyeth')()
  File "/Library/Python/2.7/site-packages/pyethereum-0.7.51_35_g2e3fc6d-py2.7.egg/pyethereum/eth.py", line 133, in main
    config = create_config()
  File "/Library/Python/2.7/site-packages/pyethereum-0.7.51_35_g2e3fc6d-py2.7.egg/pyethereum/eth.py", line 125, in create_config
    konfig.validate_config(config)
  File "/Library/Python/2.7/site-packages/pyethereum-0.7.51_35_g2e3fc6d-py2.7.egg/pyethereum/config.py", line 103, in validate_config
    assert len(config.get('network', 'node_id')) == 128  # 512bit hex encoded
AssertionError

**Comment by heikoheiko** [comment]
can you try to delete node_id from your config file? start with -L :DEBUG to get its path reported.

**Comment by scottzer0** [comment]
okay.  what config file though?  (not that familiar with pyethereum)

**Comment by heikoheiko** [comment]
on osx:
`/Users/<username>/Library/Application Support/Pyethereum/config.txt`

simply delete the file if you did not change it. 
also config files can also be used by invoking with the `-C <path>` option.

**Comment by scottzer0** [comment]
i still get the same error.  : (

**Comment by heikoheiko** [comment]
you probably have old incompatible data. best is to delete the default data dir:

`/Users/<username>/Library/Application Support/Pyethereum/`

**Comment by scottzer0** [comment]
this worked.  thanks.

also, does pyethereum have jsonrpc support?

**Comment by heikoheiko** [comment]
no not yet. but it features a restful api, which should be accessible at localhost:30203

see 
https://github.com/ethereum/pyethereum/blob/develop/pyethereum/apiserver.py
and
https://github.com/ethereum/pyethereum/blob/develop/pyethereum/ethclient.py
