### ISSUE TITLE
Allow string with state test as input for test/test_state.py

### ISSUE THREAD

**Issue by CJentzsch** [ethereum/pyethereum#213]
for the random state tests simulations I need an executable which behaves exactly as test/test_vm.py, except of taking a state test as input instead of a vm test.
Currently test/test_state.py only takes the file name as input. And it should return 0/1 for succes or failure.

**Comment by CJentzsch** [comment]
Currently also random vm tests are not working for the same reason. Only a filename is accpeted as input parameter, but no string of the test. (Reason: During the test simulation I do not want to write/read to the filesystem, I try to get everything in the cache for performance reasons)

**Comment by jnnk** [comment]
Does 4eba5a43ad643b78de7109d0847ff2599a72c996 help? With this commit `test_state.py` and `test_vm.py` expect a fixture via stdin if they are called without an argument (otherwise they read the fixture from disk, as before). Example:

```python tests/test_state.py < fixtures/StateTests/stBlockHashTest.json```

**Comment by CJentzsch** [comment]
Almost. I need to get good performance during the test simulation I do not want to write to disk or read from disk. I need this to work:
python tests/test_state.py '<contents of the json file>' .
So for example:
python_test/test_state.py '{
    "add11" : {
        "env" : {
            "currentCoinbase" : "2adc25665018aa1fe0e6bc666dac8fc2697ff9ba",
            "currentDifficulty" : "256",
            "currentGasLimit" : "1000000",
            "currentNumber" : "0",
            "currentTimestamp" : 1,
            "previousHash" : "5e20a0453cecd065ea59c37ac63e079ee08998b6045136a8ce6635c7912ec0b6"
        },
        "logs" : [
        ],
        "out" : "0x",
        "post" : {
            "095e7baea6a6c7c4c2dfeb977efac326af552d87" : {
                "balance" : "1000000000000100000",
                "code" : "0x6001600101600055",
                "nonce" : "0",
                "storage" : {
                    "0x" : "0x02"
                }
            },
            "2adc25665018aa1fe0e6bc666dac8fc2697ff9ba" : {
                "balance" : "41012",
                "code" : "0x",
                "nonce" : "0",
                "storage" : {
                }
            },
            "a94f5374fce5edbc8e2a8697c15331677e6ebf0b" : {
                "balance" : "999999999999858988",
                "code" : "0x",
                "nonce" : "1",
                "storage" : {
                }
            }
        },
        "postStateRoot" : "17454a767e5f04461256f3812ffca930443c04a47d05ce3f38940c4a14b8c479",
        "pre" : {
            "095e7baea6a6c7c4c2dfeb977efac326af552d87" : {
                "balance" : "1000000000000000000",
                "code" : "0x6001600101600055",
                "nonce" : "0",
                "storage" : {
                }
            },
            "a94f5374fce5edbc8e2a8697c15331677e6ebf0b" : {
                "balance" : "1000000000000000000",
                "code" : "0x",
                "nonce" : "0",
                "storage" : {
                }
            }
        },
        "transaction" : {
            "data" : "",
            "gasLimit" : "400000",
            "gasPrice" : "1",
            "nonce" : "0",
            "secretKey" : "45a915e4d060149eb4365960e6a7a45f334393093061116b197e3240065ff2d8",
            "to" : "095e7baea6a6c7c4c2dfeb977efac326af552d87",
            "value" : "100000"
        }
    }
}'

**Comment by CJentzsch** [comment]
My bash script looks as follows:
TEST="$(~/software/Ethereum/cpp-ethereum/build/test/createRandomTest)"

	# test pyethereum
	
	 OUTPUT_PYTHON="$(python ./tests/test_vm.py < $TEST)"
	 RESULT_PYTHON=$?

In TEST the content of the json file is stored. I did not work properly (also  OUTPUT_PYTHON="$(python ./tests/test_vm.py "$TEST")" , the original veriosn ,does not work anymore)

**Comment by jnnk** [comment]
This should work:
``OUTPUT_PYTHON="$(python ./tests/test_vm.py <<< $TEST)"``

**Comment by CJentzsch** [comment]
it works, how can I disable the trace?

**Comment by jnnk** [comment]
With the --notrace option:
``OUTPUT_PYTHON="$(python ./tests/test_vm.py --notrace <<< $TEST)"``
This didn't work before (as you might have noticed), but I have just fixed it in the develop branch. Please pull the changes.

**Comment by CJentzsch** [comment]
Thanks!

**Comment by CJentzsch** [comment]
with latest develop I get the following error:
  File "./tests/test_vm.py", line 4, in <module>
    import pytest
ImportError: No module named pytest
