### ISSUE TITLE
Error in setup.py

### ISSUE THREAD

**Issue by vibhor1403** [ethereum/pyethereum#232]
I am getting following error related to RLP when installing pythereum, using command
python setup.py install

These are the last few lines of above command's output:
Processing dependencies for pyethereum==0.8.52-113-ga6f6299
Searching for rlp>=0.3.2
Reading https://pypi.python.org/simple/rlp/
Best match: rlp 0.3.2
Downloading https://pypi.python.org/packages/source/r/rlp/rlp-0.3.2.tar.gz#md5=8b984ae2aaf1a6aa38f3f08c4551610a
Processing rlp-0.3.2.tar.gz
Writing /tmp/easy_install-rBnneL/rlp-0.3.2/setup.cfg
Running rlp-0.3.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-rBnneL/rlp-0.3.2/egg-dist-tmp-VNeHqm
error: [Errno 2] No such file or directory: 'README.md'

Also, in the start these two warnings came. Will those have effect on the setup later??
warning: no files found matching 'features/*.feature'
warning: no files found matching 'features/steps/*.py'

**Comment by heikoheiko** [comment]
fixed in cfb4b700ea1e588d6bac7091e9db4a1570e3334a

should work with new rlp version (rlp 0.3.3)
