### ISSUE TITLE
self.hash == TypeError: Can't convert 'bytes' object to str implicitly

### ISSUE THREAD

**Issue by jarradh** [ethereum/pyethereum#252]
in block.py
495:  'validated:' + self.hash not in db) and
569: self.db.put('validated:' + self.hash, '1')

Does not serialize to string properly in python3

**Comment by jarradh** [comment]
tried bytes_to_str() and various .encode(...) with no success.

**Comment by heikoheiko** [comment]
in ethereum almost everything is bytes or long. 
try:
assert isinstance(bytes, self.hash)
self.db.put(**b**'validated:' + self.hash, '1')

**Comment by jarradh** [comment]
ahh amazing , added it to pull
