### ISSUE TITLE
mkcache from pyethash

### ISSUE THREAD

**Issue by abitfan** [ethereum/pyethereum#259]
Hi,

I'm getting a TypeError at https://github.com/ethereum/pyethereum/blob/develop/ethereum/ethpow.py#L45 (function takes 2 arguments (1 given)) 
It looks like theres an incompatibility between ethash and pyethash regarding mkcache
https://github.com/ethereum/pyethereum/blob/develop/ethereum/ethpow.py#L18-L27
the latter requires two arguments https://github.com/ethereum/ethash/blob/master/src/python/core.c#L20

Thanks

**Comment by heikoheiko** [comment]
Which python version are you using?

**Comment by pipermerriam** [comment]
I got this on python 2.7 and 3.4 with pyethereum installed from master

**Comment by pipermerriam** [comment]
Also, installing pyethash from master fixed this for me.

**Comment by heikoheiko** [comment]
The pypi package needs to be updated (and probably renamed). 

@vbuterin i currently have no write permissions to the ethash repo.

**Comment by heikoheiko** [comment]
fixed with new pypi package https://pypi.python.org/pypi/pyethash
