### ISSUE TITLE
remove struclog dependency

### ISSUE THREAD

**Issue by heikoheiko** [ethereum/pyethereum#267]
goal: get rid of unnecessary 3rd party libraries. 

we use structlog in order to generate structured logs. presumably we can have the same functionality by writing a thin wrapper around the stdlib logging module.

task: extend slogging.py to support the current feature set (see tests) w/o the structlog module.
https://github.com/ethereum/pyethereum/blob/develop/ethereum/slogging.py 
https://github.com/ethereum/pyethereum/blob/develop/ethereum/tests/test_logging.py
https://structlog.readthedocs.org/

**Comment by ulope** [comment]
This has already been fixed by #282
