### ISSUE TITLE
Consensus Vulnerability

### ISSUE THREAD

**Issue by ddworken** [ethereum/pyethereum#271]
PyEthereum is vulnerable to a consensus vulnerability since it uses len() to calculate the number of bytes in the ```extra_data``` field of each block. len returns the number of characters in the string, not the number of bytes. This does not match the behavior of CPP-Ethereum, Go-Ethereum, and EthereumJ. 

This allows for an attacker to set an ```extra_data``` up to 128 bytes in size (4 bytes per unicode character) and have PyEthereum accept it.

**Comment by ddworken** [comment]
For a simple example of how this fails, see [here](https://repl.it/BAeZ).

**Comment by vbuterin** [comment]
In your example, the string actually contains only 14 characters if you count manually, so len seems to be working as intended; I think python is using an encoding other than utf-8 internally automatically. Particularly, see:

>>> s = "¡utf-8 is fun!" 
>>> s
'\xc2\xa1utf-8 is fun!'

You could get around this by supplying a string in unicode, but that fails at the RLP encoding stage:

>>> g = ethereum.blocks.genesis(ethereum.db.EphemDB())
>>> g.extra_data = u'™'
>>> rlp.encode(g)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/rlp-0.3.8-py2.7.egg/rlp/codec.py", line 41, in encode
    return encode_raw(item)
  File "/usr/local/lib/python2.7/dist-packages/rlp-0.3.8-py2.7.egg/rlp/codec.py", line 60, in encode_raw
    payload = b''.join(map(encode_raw, item))
  File "/usr/local/lib/python2.7/dist-packages/rlp-0.3.8-py2.7.egg/rlp/codec.py", line 60, in encode_raw
    payload = b''.join(map(encode_raw, item))
  File "/usr/local/lib/python2.7/dist-packages/rlp-0.3.8-py2.7.egg/rlp/codec.py", line 57, in encode_raw
    payload = str_to_bytes(item)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2122' in position 0: ordinal not in range(128)

So the block should never get saved to disk. That said, for additional safety, I added to_string around extra_data as a wrapper: https://github.com/ethereum/pyethereum/commit/9da62da8b0ff3de7be2b3cd5772579bd084e4778

**Comment by heikoheiko** [comment]
We are only dealing with bytes (as it's called in py3) in pyethereum.
