### ISSUE TITLE
implement difficulty tests

### ISSUE THREAD

**Issue by heikoheiko** [ethereum/pyethereum#273]
2cd01ff1b3720649cfeb06ad4689b6e66d3910f1

 https://github.com/ethereum/tests/blob/develop/BasicTests/difficulty.json

**Comment by RomanZacharia** [comment]
@heikoheiko Is this issue resolved?

**Comment by RomanZacharia** [comment]
Python interface for these tests needs to be implemented.

**Comment by RomanZacharia** [comment]
All the difficulty tests were implemented. Please pull my changes.
