### ISSUE TITLE
compilation failed

### ISSUE THREAD

**Issue by mtgran** [ethereum/pyethereum#286]
Hi,

I get a "compilation failed" error message when I run "truffle deploy". It deals with the _solidity.py library, therefore I am reporting the error here.

> Server error:   File "/home/m9000/.local/lib/python2.7/site-packages/ethereum/_solidity.py", line 86, in combined | CompileError: compilation failed

The solc version is 0.1.2-0 and python is 2.7.9. The used contract is syntactically correct.

**Comment by ethers** [comment]
what commit of pyethereum do you have?  compilation was fixed but after v1.0.0 so try this:
https://github.com/ethereum/pyethereum/commit/27e38c3c3cb0c357f06664c6ad5ea71d57b4a1d2
