### ISSUE TITLE
Install failing (Mac OSX)

### ISSUE THREAD

**Issue by nicosandller** [ethereum/pyethereum#292]
I'm trying to install pyethereum by runing :

`sudo python setup.py install --user`

but it fails to install by returning:

```command
Installed /Library/Python/2.7/site-packages/ethereum-1.0.6-py2.7.egg
Processing dependencies for ethereum==1.0.6
Searching for scrypt
Reading https://pypi.python.org/simple/scrypt/
Best match: scrypt 0.7.1
Downloading https://pypi.python.org/packages/source/s/scrypt/scrypt-0.7.1.tar.gz#md5=9feb713f183e11caa940e8ec71cf1361
Processing scrypt-0.7.1.tar.gz
Writing /tmp/easy_install-tYX2NZ/scrypt-0.7.1/setup.cfg
Running scrypt-0.7.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-tYX2NZ/scrypt-0.7.1/egg-dist-tmp-Qs5vgS
scrypt-1.1.6/lib/crypto/crypto_aesctr.c:38:10: fatal error: 'openssl/aes.h'
      file not found
#include <openssl/aes.h>
         ^
1 error generated.
error: Setup script exited with error: command 'cc' failed with exit status 1
```

am I missing something? I checked and OpenSSL is installed on my computer, and it seems to be working.  I see that the build is not passing for OSX, is this related?

Thanks

**Comment by yanik5** [comment]
@nicosandller what was the problem? I had the same

**Comment by nicosandller** [comment]
@yanik5  I don't remember :S. I think I just gave up and installed it on an Ubuntu VM. You should also try koding.com, it came in pretty handy.

**Comment by conor10** [comment]
You can work around this issue by installing scrypt manually via pip first and pointing it to the OpenSSL library.

`env LDFLAGS="-L$(brew --prefix openssl)/lib" CFLAGS="-I$(brew --prefix openssl)/include" pip install scrypt`

**Comment by kimdhamilton** [comment]
@conor10's workaround fixed the installation on mac for me

**Comment by pipermerriam** [comment]
I believe you can also do `brew link openssl --force` to fix this for future install without having to do the env variables.

**Comment by ridwannaibi** [comment]
@conor10 @kimdhamilton Please can you explain how I achieve this, I a newbie on terminal. Thanks

**Comment by husky-parul** [comment]
I am trying to install pyethereum on OS Sierra and getting the below error.

Installed /Users/singh.p/Library/Python/2.7/lib/python/site-packages/ethereum-2.0.4-py2.7.egg
Processing dependencies for ethereum==2.0.4
Searching for py-ecc
Reading https://pypi.python.org/simple/py_ecc/
Reading https://pypi.python.org/simple/py-ecc/
Couldn't find index page for 'py_ecc' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or download links found for py-ecc
error: Could not find suitable distribution for Requirement.parse('py-ecc')

**Comment by grodobean** [comment]
I got around the OpenSSL error by doing sudo env LDFLAGS="-L$(brew --prefix openssl)/lib" CFLAGS="-I$(brew --prefix openssl)/include" python3 setup.py install but now I'm coming across, "error: [Errno 2] No such file or directory: 'README.md'
"

**Comment by Ram-Crypto** [comment]
i m trying to install pyethereum using following command..
sudo python setup.py install
but i am getting error......

Installed /usr/local/lib/python2.7/dist-packages/ethereum-2.0.4-py2.7.egg
Processing dependencies for ethereum==2.0.4
Searching for py_ecc
Reading https://pypi.python.org/simple/py_ecc/
Downloading https://pypi.python.org/packages/12/ad/b4d6de8212495b8959e84781ef3cbc5ed8fdadfd3b68b5f50275205bbc3e/py_ecc-1.1.2.tar.gz#md5=c0f0d77219eb6cb0a49460d7728ff958
Best match: py-ecc 1.1.2
Processing py_ecc-1.1.2.tar.gz
Writing /tmp/easy_install-01gaM0/py_ecc-1.1.2/setup.cfg
Running py_ecc-1.1.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-01gaM0/py_ecc-1.1.2/egg-dist-tmp-RGFja6
error: [Errno 2] No such file or directory: 'README.md'
please solve...

**Comment by d4tech** [comment]
Do check if you have libtools installed `brew install libtools`.

**Comment by Tuanm** [comment]
Same problem when installing ethereum on WSL2.
