### ISSUE TITLE
how to install keccak module for sha3_256 using pypy

### ISSUE THREAD

**Issue by psalami** [ethereum/pyethereum#293]
When running under pypy, I cannot find the keccak module (so it falls back to using sha3 module which doesn't work). Is there a pip package that satisfies the requirement that we can add to requirements.txt? (see d740d59b4492c78ae84b687f756ce1949d78dbde)

**Comment by czepluch** [comment]
We are working on this fix in a branch right now. Will be merged soon.

**Comment by psalami** [comment]
K, thx. In the meantime I am trying to run by adding pykeccak==0.2.1 to my requirements.txt. Does that look right to you? There seems to be an issue with the assert in [utils.py#L106](https://github.com/ethereum/pyethereum/blob/develop/ethereum/utils.py#L106).
Do you have any recommendations on how to run under pypy in the meantime?

**Comment by czepluch** [comment]
Yeah. That's one of the things were changing too, to work properly. So it shouldn't work for you unless you change some naming. I am just in my smart phone right now, so sorry for my primitive answer.

**Comment by psalami** [comment]
no problem, thanks! I'll see if I can figure out the naming changes necessary.

**Comment by czepluch** [comment]
Cool. I will be online in the morning if you need any help.

**Comment by czepluch** [comment]
This was fixed with https://github.com/ethereum/pyethereum/pull/295
