### ISSUE TITLE
Outdated pip package

### ISSUE THREAD

**Issue by musalbas** [ethereum/pyethereum#309]
The pip package for pyethereum is extremely outdated and contains an old ABI that is incompatible with current Ethereum protocols. (For example, the code for encoding method data does not use a head/tail mechanism.) https://pypi.python.org/pypi/pyethereum

**Comment by ulope** [comment]
The PyPI package name has been renamed to `ethereum` quite a while ago.
We should probably delete the outdated package, or replace it with one that outputs warning message notifying the user of the rename, @heikoheiko what do you think?

**Comment by heikoheiko** [comment]
removed
