### ISSUE TITLE
Make the testing pass

### ISSUE THREAD

**Issue by RomanZacharia** [ethereum/pyethereum#317]
Travis testing on the develop branch failed.
konradkonrad [8:28 PM] 
before I got distracted, my understanding was, that there were some new, not yet supported, testcases imported through the `fixtures`-git-submodule. IF that is true, it would be nice to bisect the submodule versions and find the last supported test-scenario.

the goal should be:
- make sure, PRs against `develop` have a chance to build (again)
- make sure, development against newer test-cases find a new place (e.g. `homestead`-branch, IF everything above is true and this is the problem with the test-cases)

**Comment by RomanZacharia** [comment]
Some assistance needed in reproducing locally.
My attempt to run the tests locally crashes even earlier than travis:
running them as
pyethereum/ethereum/tests$ python test_transactions.py ../../fixtures/TransactionTests/

gives 
.....
Testing: ../../fixtures/TransactionTests/ttTransactionTest.json TransactionWithRvalueHigh
[libsecp256k1] illegal argument: !secp256k1_fe_is_zero(&ge->x)
Aborted (core dumped)

I have c_secp256k1-0.0.8 installed. May be some other version required? Or I'm executing tests not properly?

**Comment by janx** [comment]
I think the interface is changed in pysecp256k1 0.0.8 (e.g. `ecdsa_sign_raw` no longer exists), but I'm not sure which version should be used. 

[pybitcointools](https://github.com/vbuterin/pybitcointools) works for me. see: https://github.com/ethereum/pyethereum/blob/develop/ethereum/transactions.py#L20

New fixtures is just one source of test breakers. If you checkout an old version like v1.0.8 which contains no new fixtures like 'Homestead', some tests still fail.

+1 for healthy tests :pill:

**Comment by RomanZacharia** [comment]
Bisecting identified that the issue first showed up in the FIXTURES commit bedbe0792a681a57a08c46908aa2c29e80e0af9b
But testing the recent version of the pyethereum develop branch with the previous commit (to the bedbe0792a681a57a08c46908aa2c29e80e0af9b) also fails due to other errors.

**Comment by RomanZacharia** [comment]
@konradkonrad  Need to create a homestead branch now, to continue development against the recent unit tests in it.

The tests in the develop branch will be rolled back to the commit 8c39257df28b8b49368249f43c836d419d5f0bf2 afterwards.

**Comment by RomanZacharia** [comment]
Update:
The commit changed to a6382c20817e6b8ba539a3cba396ec0d79a4a1c3 and the test_vm_failing.py was removed.
The development with testing against the most recent fixtures and test_vm_failed.py should be continued in the homestead branch.

**Comment by RomanZacharia** [comment]
I fixed the checks for the signature S value and the tests has passed.
