### ISSUE TITLE
ValueOutOfBounds exception in test_ecrecover

### ISSUE THREAD

**Issue by ulope** [ethereum/pyethereum#331]
Commit 063738548dec9aeb64bcb9778e0ef13049f5354a introduced a test failure in `ethereum/tests/test_contracts.py::test_ecrecover`. 

I've reverted that commit for now so that we can release ethereum 1.2.1

@janx Could you please take a look at this?

**Comment by janx** [comment]
@ulope please have a look at https://github.com/ethereum/pyethereum/pull/326

**Comment by ulope** [comment]
Fixed via #326
