### ISSUE TITLE
`OUT OF GAS` error, when running test_registry.py 

### ISSUE THREAD

**Issue by RomanZacharia** [ethereum/pyethereum#349]
the issue is that we get an `OUT OF GAS` error, when running the following test: https://github.com/brainbot-com/raiden/blob/truffle/raiden/smart_contracts/tests/test_registry.py using `py.test`. We got it working with Hydrachain, but not with tester.py.

**Comment by heikoheiko** [comment]
closing. please reopen if you can provide a minimal failing test.
