### ISSUE TITLE
lazy_encode fails to encode storage changes

### ISSUE THREAD

**Issue by hackaugusto** [ethereum/pyethereum#352]
Storage changes can have four items:
https://github.com/ethereum/pyethereum/blob/develop/ethereum/blocks.py#L1017

The `lazy_encode` is only evaluated if the logging is set to `TRACE`:
https://github.com/ethereum/pyethereum/blob/develop/ethereum/blocks.py#L1032

`lazy_encode` assumes that all items in the list have length 3:
https://github.com/ethereum/pyethereum/blob/develop/ethereum/blocks.py#L42

**Comment by heikoheiko** [comment]
@konradkonrad ---^
