### ISSUE TITLE
make pyethereum available via pip install

### ISSUE THREAD

**Issue by drandreaskrueger** [ethereum/pyethereum#358]
Tried to install an old version via pip because of [this install error with the newest version](https://github.com/ethereum/pyethereum/issues/356#issuecomment-227002725), but:

    pip install pyethereum

```
Downloading/unpacking pyethereum
  Could not find any downloads that satisfy the requirement pyethereum
Cleaning up...
No distributions at all found for pyethereum
```

Please make pyethereum available via `pip install`, thanks.

**Comment by drandreaskrueger** [comment]
Found it, thanks

    pip install ethereum

Please create a readme at pyethereum. Thanks.

**Comment by konradkonrad** [comment]
@drandreaskrueger yeah, we went with the more generic name. 
> Please execute some `migrated.py` infotext at `pip install pyethereum`

Can you provide us with an example project to push to `pyethereum`?

**Comment by drandreaskrueger** [comment]
Not sure I understand.

Usually when I `pip install` I do not check the [pypi page](https://pypi.python.org/pypi/pyethereum). Now I don't remember anymore what I did a month ago, but for sure it took me some time to get your name change - otherwise I would not have opened this issue here.

So what I was thinking back then was to have a dummy project at `pip install pyethereum` which at install time just displays the message "is now called differently, use `pip install ethereum`".

Or perhaps there is an official way to redirect one pypi package to another one?

**Comment by konradkonrad** [comment]
We never changed the name. I think the confusion comes from the source repository being called `pyethereum` but the pip/pypi package going by the generic name `ethereum`.

Your response with `migrated.py` sounded as if you knew a standard way to have pip/pypi display an infotext. I wanted to ask you, if you could provide us with the code for doing so?

**Comment by drandreaskrueger** [comment]
Ah, thanks for the clarification. Naming gremlins :-)

> sounded as if you knew a standard way 
Nope, sorry.

I just thought, it should be possible somehow.

**Comment by ulope** [comment]
There used to be a package on PyPI called `pyethereum` but that was a *very* old version. @heikoheiko deleted it a while back to avoid confusion.

I supposed it would not be too difficult to put together a setup.py that fails upon installation with a message of some sort. If it's something we want to put time into is another question.

**Comment by drandreaskrueger** [comment]
:-)
