### ISSUE TITLE
Architecture Refactoring V2

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/pyethereum#364]
### What is the problem.

The `pyethereum` library is large and complex. It houses many different pieces of functionality related to interacting with Ethereum based systems.

### Proposed change

I would like to suggest splitting the `pyethereum` library into a few separate
repositories.  I don't know if these are the correct dividing lines, but based
on my knowledge of the codebase, they seem like a good place to start.

* Solidity Wrapper: `_solidity.py`
* EVM: `vm.py`
* Blocks/Accounts/Receipts/etc: `blocks.py`
* Transactions: `transactions.py`
* Tester: `tester.py`
* Contracts and ABI: `abi.py`

**Benefits**

* Isolation of functionality along natural lines.  This should reduce overall complexity of each portion of the code.
* Simplify installation of the library. The Contract and ABI based operations don't actually need the underlying cryptographic libraries necessary for Transaction signing.
* Untangles circular dependencies.  Currently the `serpent` and `pyethereum` codebases have a cirular dependency in their testing dependencies.

**Drawbacks**

* Maintenance overhead.  If a bug is found in an upstream dependency then it will take coordination across multiple repositories to get it fixed.
* Slower iteration speed.  I know that @vbuterin uses this repository to iterate quickly on his research.  Having the code split across repositories will add some overhead to his process.

### Proposed Roadmap

I would suggest decoupling dependencies in the following steps.

#### 1. Solidity

`_solidity.py`

This module only depends on `ethereum/utils.py::to_string`.  Separating it will provide an easy way to practice extracting code to another package.

#### 2. Contract and ABI

`abi.py`

This module only depends on `ethereum/utils.py`.  It would provide python based
tools for Ethereum interactions without requiring installation of the other
more complex code or system dependencies.

#### 3. VM

`vm.py`, `fast_vm.py`, `opcodes.py`

This module is somewhat *special* in that it requires attention to performance
and has a very specific specification.  It has very few dependencies on the
remainder of the `pyethereum` codebase.

#### 4. Transactions

`transactions.py`, `bloom.py`

This module appears to be the only one that requires the underlying `libffi`
cryptographic library (for tx signing).

#### 5. Blocks (and other data structures)

`blocks.py` (and everything else `processblock/trie/pruning_trie/etc`)

This stuff is not extracted but rather remains in the main `pyethereum`
repository and ends up depending on the other pieces of extracted code.

#### 6. Tester

I'm not entirely sure how to unravel this dependency.  Suggestions welcome.

The biggest *issue* with this modules is that it depends on almost all of the other code **and** it is used to test most of the other code which introduces a circular dependency chain.

### Deprecation plan.

This re-architecture would happen iteratively with the following deprecation
plan.

* Extract code into standalone lib.
* Change existing `pyethereum` code to *wrap* the new standalone library code and raise deprecation warnings.
* Change `pyethereum` code to depend on the new library.
* Remove deprecated functions after 1-2 major releases.

### A Cute Animal Picture For Your Troubles

![baby-badger](https://cloud.githubusercontent.com/assets/824194/16204920/6871eb38-36de-11e6-84f1-85637227815f.jpg)

**Comment by heikoheiko** [comment]
I'm not convinced that this will be a win, as keeping the current set of used repositories in sync is already a challenge. Repos should only exist for code that is used by multiple independent projects. 

>  Isolation of functionality along natural lines. This should reduce overall complexity of each portion of the code.

An alternative to achieve this would be to use sub packages in the ethereum package, all with their own specific test package. 

>  Simplify installation of the library. The Contract and ABI based operations don't actually need the underlying cryptographic libraries necessary for Transaction signing.

secp256k1 is needed for the ecrecover precompiled contract 
but we could make `secp256k1` optional,  only import it if available and fall back to the `bitcoin` lib.

> Untangles circular dependencies. Currently the serpent and pyethereum codebases have a cirular dependency in their testing dependencies.

I'd be happy if serpent was not a test requirement. A solution could be to directly work with compiled code / json-abis in the tests. A script to generate and update the compiled data would be needed.

**Comment by ulope** [comment]
I agree with Heiko. 

It's already quite annoying and time consuming to release a new PyEthApp version if for example pyrlp was updated:
* Update pyrlp
 * Tag new version
 * Push changes
 * Wait for travis to build and hopefully push to PyPI
* Update Ethereum
 * Update requirements
 * Tag new version
 * Push changes
 * Wait for travis to build and hopefully push to PyPI
* Update PyEthApp
 * Update requirements
 * Tag new version
 * Push changes
 * Wait for travis to build and hopefully push to PyPI

This can easily take an hour or more for even the simplest of changes. I don't see the situation improving by splitting the code into even more libraries.

Regarding simplicity of installation:
That would be much improved if we could provide precompiled binary packages for the most common platforms. I'm already investigating various ways in which we could achieve that.

**Comment by pipermerriam** [comment]
i'm going to shelve this idea for now.  Thanks for the feedback.

**Comment by heikoheiko** [comment]
well the general intention was not wrong and i think that sub packages could be a good start to improve the accessibility of the code base.

**Comment by pipermerriam** [comment]
@heikoheiko I plan to revisit this after the next major network release has settled.  In the meantime I've got an entire parallel set of python based ethereum tooling that's sort of building this architecture on it's own.
