### ISSUE TITLE
tester has been broken

### ISSUE THREAD

**Issue by chfast** [ethereum/pyethereum#370]
The `ethereum.tester` has been broken in 1.3.3 (in 1.3.2 it works):

```
  File "/home/ubuntu/virtualenvs/venv-system/local/lib/python2.7/site-packages/ethereum/tester.py", line 114, in __init__
    for function_name in self.translator.function_data:
AttributeError: 'str' object has no attribute 'function_data'
```

**Comment by hackaugusto** [comment]
There is not enough detail to figure out the problem. ABIContract could be instantiated at line [227](https://github.com/ethereum/pyethereum/blob/v1.3.3/ethereum/tester.py#L227), but that path always use a ContractTranslator, not a `str` object. Could you provide a minimum failing test?

Also, have you tried a more up-to-date version? The current version is [1.3.6](https://pypi.python.org/pypi/ethereum/1.3.6)

**Comment by chfast** [comment]
The test is from https://github.com/imapp-pl/ethereum-contracts/blob/master/tests/test_bankofdeposit.py#L43. It might be a change in the ABIContract constructor, I pass a string containing JSON there.

The API change is precisely in version 1.3.3. I tested everyone in from 1.3.0 to 1.3.6 and 1.2.

Exemple builds: https://circleci.com/gh/imapp-pl/ethereum-contracts

If it is still not enough information I will prepare a test later on.

**Comment by chfast** [comment]
Thank you.
