### ISSUE TITLE
abi_contract error: secp256k1_recovery not enabled

### ISSUE THREAD

**Issue by tinybike** [ethereum/pyethereum#392]
I'm having difficulty getting recent versions of pyethereum to work.  The last good commit for me is 14d0ec6d574f99a24cce71209dd97d4869d644c9.  Here is a minimal Python script (using the most recent develop commit, 01d2cef0ab1749b8914d97128d7fd901dd0e7dd5):
```python
from ethereum import tester
tester.state().abi_contract("""
def foo():
    return(1)
""")
```
When I run this, I get the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "ethereum/tester.py", line 230, in abi_contract
    **kwargs
  File "ethereum/tester.py", line 201, in contract
    address = self.evm(bytecode, sender, endowment)
  File "ethereum/tester.py", line 249, in evm
    transaction.sign(sender)
  File "ethereum/transactions.py", line 127, in sign
    pk.ecdsa_sign_recoverable(rawhash, raw=True)
  File "/usr/local/lib/python2.7/dist-packages/secp256k1-0.12.1-py2.7-linux-x86_64.egg/secp256k1/__init__.py", line 395, in ecdsa_sign_recoverable
    raise Exception("secp256k1_recovery not enabled")
Exception: secp256k1_recovery not enabled
```
I'm using Python 2.7.6 on Xubuntu 14.04.  My Serpent version is ethereum/serpent@9dc8c1ccbb169b1fb7debef5de638cc9e0f88fac.

**Comment by kobigurk** [comment]
I've just had the same issue.
I solved it using the following steps:

1. rebuilding secp256k1 with the flag `--enable-module-recovey`
2. reinstalling with `sudo make install`
3. `pip uninstall secp256k1 && pip install secp256k`

The last step is necessary because the python package copies the so from the local system.

**Comment by tinybike** [comment]
Worked for me, thanks!  Closing this issue.
