### ISSUE TITLE
Is every new transaction added to head_candidate will emit a new miner?

### ISSUE THREAD

**Issue by rjl493456442** [ethereum/pyethereum#393]
Is every new transaction added to head_candidate will emit a Miner ?
```
def add_transaction(self, tx, origin=None, force_broadcast=False):
     # add transaction to head candidate
     # balabala
    success = self.chain.add_transaction(tx)
    if success:
            self._on_new_head_candidate()
        return success
```
Is my comprehension right?

**Comment by heikoheiko** [comment]
Yes, see:
https://github.com/ethereum/pyethapp/blob/develop/pyethapp/pow_service.py#L132
https://github.com/ethereum/pyethapp/blob/develop/pyethapp/pow_service.py#L84
