### ISSUE TITLE
ecrecover is way too slow

### ISSUE THREAD

**Issue by heikoheiko** [ethereum/pyethereum#396]
the current implementation introduced in 461a88aa1ad88cf7da79414c2be2980e84b6a5c5 which uses libsecp256k1 is for some reason very slow. 

The one used before that commit is x40 faster. 

```
{'add_block': {'calls': 1000, 'total': 37.05270528793335},
 'apply_transaction': {'calls': 2321, 'total': 34.751814126968384},
 'apply_tx.ecrecover': {'calls': 2321, 'total': 21.537762880325317},
 'apply_tx.ecrecover_raw': {'calls': 2321, 'total': 0.592186450958252}}
```

The current broken ecrecover accounts for ~2/3 of the tx validation time .

**Comment by ofek** [comment]
@joeykrug @heikoheiko @ulope Fixed in #777
