### ISSUE TITLE
PyPI lists version 1.3.7 (not 1.6.0) as the latest

### ISSUE THREAD

**Issue by maurycyp** [ethereum/pyethereum#420]
https://pypi.python.org/pypi/ethereum

This appears to have happened after the Nov. 13 release.  Version 1.6.0 is still available ( https://pypi.python.org/pypi/ethereum/1.6.0 ), and I remember seeing it as the latest version a few days ago.

**Comment by ulope** [comment]
This is a problem of the current (old) PyPI UI. It always shows the latest upload independent of version number. 

The new PyPI interface shows the correct version https://pypi.org/project/ethereum/#description

Also pip correctly installs `1.6.0`
