### ISSUE TITLE
assertion error caused by rlp version upgrade

### ISSUE THREAD

**Issue by RCasatta** [ethereum/pyethereum#440]
Using the library I have an assertion error

```
assert encode_hex(sha3(b'')) == b'c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470'
AssertionError
```

This is caused by a change in rlp lib version 0.4.3 https://github.com/ethereum/pyrlp/commit/2ec0fe159652f2cf12794bd8c239a8823cf93579

since encode_hex return a string, this could not be equal to `b'something'`

I am solving by downgrading to rlp to 0.4.2

```
pip install -I rlp==0.4.2
```

**Comment by konradkonrad** [comment]
hey @RCasatta this got just recently fixed: https://github.com/ethereum/pyethereum/pull/425 -- I hope to get a new release version out soon (TM).
