### ISSUE TITLE
cffi1.9.1 update

### ISSUE THREAD

**Issue by milketh** [ethereum/pyethereum#443]
Is it possible to update the cffi version to be 1.9.1.
[https://pypi.python.org/pypi/cffi/1.9.1](https://pypi.python.org/pypi/cffi/1.9.1)

cffi1.5.2 (linux not included?)

[https://pypi.python.org/pypi/cffi/1.5.2](https://pypi.python.org/pypi/cffi/1.5.2)

thanks

  File "/usr/local/lib/python3.5/dist-packages/cffi-1.9.1-py3.5-linux-x86_64.egg/cffi/api.py", line 59, in __init__
    "version mismatch, %s != %s" % (backend.__version__, __version__)
AssertionError: version mismatch, 1.5.2 != 1.9.1

**Comment by joeykrug** [comment]
Cffi isn't a requirement afaik, closing
