### ISSUE TITLE
Upload package to pypi

### ISSUE THREAD

**Issue by reiven** [ethereum/pyethereum#711]
Hi

It will be great to have the latests version uploaded to pypi (pypi.python.org) so this package can be downloaded and installed using pip

Let me know if you need help in doing this

**Comment by ulope** [comment]
Thanks, but it's already on there. However the package is called [ethereum](https://pypi.org/project/ethereum/) on PyPI.

**Comment by reiven** [comment]
Thanks @ulope it will be great to add that information in the Readme. I can make a PR with that change.

Regards
