### ISSUE TITLE
Global name 'to_string' is not defined in block.py of ethereum/state_revamp_with_p62

### ISSUE THREAD

**Issue by ankitchiplunkar** [ethereum/pyethereum#721]
In the block.py script of ethereum/state_revamp_with_p62

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ankitchiplunkar/anaconda2/lib/python2.7/site-packages/ethereum-1.6.1-py2.7.egg/eth
ereum/block.py", line 120, in to_dict
    d[field] = to_string(getattr(self, field))
NameError: global name 'to_string' is not defined

Change the line 
from ethereum.utils import normalize_address, hash32, trie_root, \
    big_endian_int, address, int256, encode_hex, encode_int, sha3

To
from ethereum.utils import **to_string**, normalize_address, hash32, trie_root, \
    big_endian_int, address, int256, encode_hex, encode_int, sha3

**Comment by janx** [comment]
@ankitchiplunkar thanks for reporting!

Fixed on develop since state_revamp_with_p62 has been merged.
