### ISSUE TITLE
Never-failing asserts in casper_utils.py

### ISSUE THREAD

**Issue by gsalgado** [ethereum/pyethereum#727]
There are [two](https://github.com/ethereum/pyethereum/blob/develop/ethereum/casper_utils.py#L190) [places](https://github.com/ethereum/pyethereum/blob/develop/ethereum/casper_utils.py#L200) in casper_utils.py that assert the result of [apply_transaction](https://github.com/ethereum/pyethereum/blob/b53e82816f4edf3dbe463698c3c5fa2caaf1fa40/ethereum/state_transition.py#L287), but that function returns a two-tuple and they do not unpack it before asserting, so the assert will never fail

**Comment by Ray1988** [comment]
Hi Gsalgado, does #729 be merged in? thanks

**Comment by janx** [comment]
Thanks guys!
