### ISSUE TITLE
Account generation speed and installation

### ISSUE THREAD

**Issue by shauns** [ethereum/pyethereum#750]
Is there something needed other than `pip install ethereum` to optimally run this library?

`keys.make_keystore_json(...)` takes about 30s to run on a 2015 Macbook Pro. I understand account generation is [not meant to be instant][stackexchange], but if I compare to [keythereum] for instance, that takes <500ms, doing the same number of iterations of pbkdf2.

Is this just a python thing maybe or is there an optional library to install that runs things natively?

```console
$ python --version
Python 3.6.1
$ pip freeze
bitcoin==1.1.42
cffi==1.10.0
ethereum==1.6.1
pbkdf2==1.3
pycparser==2.17
pycryptodome==3.4.6
pyethash==0.1.27
pysha3==1.0.2
PyYAML==3.12
repoze.lru==0.6
rlp==0.5.1
scrypt==0.8.0
secp256k1==0.13.2
```

[stackexchange]: https://ethereum.stackexchange.com/questions/5983/generating-accounts-with-pyethereum-is-insanely-slow
[keythereum]: https://www.npmjs.com/package/keythereum

**Comment by joeykrug** [comment]
I think it's just slow, looks like Vitalik is moving some of the account generation stuff to a separate python lib and making it faster

**Comment by AndreMiras** [comment]
I also have the feeling that there's something not quite right. I didn't take time profiling it. I'm using pyethereum for an Android app (weird I know). And if I compare with other Ethereum Android apps, mine is much slower to generate the account. Yes I know Python is not as fast as Java and all of that. So yes I've played with `PBKDF2_CONSTANTS["c"]` to decrease the pbkdf2 iterations, but still. I also don't think the other apps decreased it as much as I did. And I also think they perform account creation on device just like I do.
It might just be the [pbkdf2](https://www.dlitz.net/software/python-pbkdf2/) module we are using and perhaps it could be interesting to make it possible to optionally use the [python-fastpbkdf2](https://github.com/Ayrx/python-fastpbkdf2) module. It's a binding for the [fastpbkdf2](https://github.com/ctz/fastpbkdf2) (C implementation).
Again it's just some first thoughts, but I didn't investigate.

**Comment by AndreMiras** [comment]
So I believe [ethereum.tools.keys.make_keystore_json()](https://github.com/ethereum/pyethereum/blob/v2.3.1/ethereum/tools/keys.py#L122) should raise a `DeprecationWarning` in favor to [eth_keyfile.keyfile.create_keyfile_json()](https://github.com/ethereum/eth-keyfile/blob/v0.5.1/eth_keyfile/keyfile.py#L37) which is way more faster.
So now it's more an issue with [pyethapp/accounts.new()](https://github.com/ethereum/pyethapp/blob/v1.5.0/pyethapp/accounts.py#L62) which is still using the old version. I'll send a pull request if I find time for it.
