### ISSUE TITLE
make_keystore_json broken on Python 3

### ISSUE THREAD

**Issue by ulope** [ethereum/pyethereum#758]
There is code in [`make_keystore_json`](https://github.com/ethereum/pyethereum/blob/develop/ethereum/tools/keys.py#L118) that [manually builds a uuid](https://github.com/ethereum/pyethereum/blob/develop/ethereum/tools/keys.py#L138) from the output of `encode_hex()` which returns a string in recent versions. This then breaks on the `b'-'.join(...)` call.

I'd suggest to simply use the builtin `uuid` module and replace [L137-138](https://github.com/ethereum/pyethereum/blob/develop/ethereum/tools/keys.py#L137-L138) with:
```
key_uuid = str(uuid.uuid4()).encode("ascii")
```

**Comment by ongrid** [comment]
Hi @ulope! As discussed in https://gitter.im/ethereum/pyethereum (Jul 27 17:39) 
@vbuterin recently started moving key-related stuff to a separate repo, http://github.com/ethereum/pyeth_keys 
Should be fixed there after refactoring done.
