### ISSUE TITLE
Error on installation on Osx Sierra

### ISSUE THREAD

**Issue by husky-parul** [ethereum/pyethereum#759]
Processing dependencies for ethereum==2.0.4
Searching for py-ecc
Reading https://pypi.python.org/simple/py_ecc/
Reading https://pypi.python.org/simple/py-ecc/
Couldn't find index page for 'py_ecc' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or download links found for py-ecc
error: Could not find suitable distribution for Requirement.parse('py-ecc')

**Comment by danzipie** [comment]
That's because last commit https://github.com/ethereum/pyethereum/commit/ecb14c937a0b6cb0a0dc4f06be3a88e6d53dcce3 substituted the dependency from 'bitcoin' module to a new module 'py_ecc', but py_ecc it is not uploaded in PyPi yet.

**Comment by whardier** [comment]
See: https://github.com/ethereum/py_pairing

**Comment by beaugunderson** [comment]
I went ahead and [published](https://pypi.python.org/pypi/py_ecc/1.0.0) `py_ecc` to PyPi (and made @vbuterin an owner) so this can be closed ✨
