### ISSUE TITLE
Setup error on Mac OSX

### ISSUE THREAD

**Issue by jibuji** [ethereum/pyethereum#762]
I am using the latest master branch, after run `python setup.py install`, found error:

Installed /private/var/folders/xy/hq6d84p17ks748kc_3d1pp2r0000gn/T/easy_install-zF6tsG/secp256k1-0.13.2/.eggs/pycparser-2.17-py2.7.egg
Installed libsecp256k1 is unusable falling back to bundled version.
Using bundled libsecp256k1
build/temp.macosx-10.11-x86_64-2.7/_libsecp256k1.c:434:10: fatal error:
      'secp256k1_recovery.h' file not found
#include <secp256k1_recovery.h>
         ^
1 error generated.
error: Setup script exited with error: command 'clang' failed with exit status 1

**Comment by ofek** [comment]
@jibuji Can you please try again using the develop branch now that #777 has landed?

**Comment by joeykrug** [comment]
I had the same issue before 777, works now
