### ISSUE TITLE
Readme.md Error When Trying To Install On Mac OS X

### ISSUE THREAD

**Issue by grodobean** [ethereum/pyethereum#764]
When executing 'sudo env LDFLAGS="-L$(brew --prefix openssl)/lib" CFLAGS="-I$(brew --prefix openssl)/include" python3 setup.py' install I come across this error before the installation finishes:''error: [Errno 2] No such file or directory: 'README.md'"

**Comment by grodobean** [comment]
****

**Comment by bblanque** [comment]
Had the same issue installing on Ubuntu 16.04.2 LTS (Xenial)

**Comment by TomMadelin** [comment]
Same issue on Ubuntu 16.04.2 compiling for Python 2.7

**Comment by kcar1** [comment]
Same issue on Ubuntu 14.04 LTS Python 2.7

**Comment by karlfloersch** [comment]
Try installing https://github.com/ethereum/py_pairing manually and then try again. I believe this is what solved this issue for me

```
pip install git+https://github.com/ethereum/py_pairing
```
