### ISSUE TITLE
You break logging configs

### ISSUE THREAD

**Issue by mezrin** [ethereum/pyethereum#765]
https://github.com/ethereum/pyethereum/blob/develop/ethereum/slogging.py#L38

What is it !?!?
I've spent 5 hours to figure out that you lib reconfigures logging facility
This is weird

You break logging configuration of other projects
There is no reason to break logging config of all other projects just because you want pretty log records in your library

**Comment by joeykrug** [comment]
#760 has a good description of this, closing this issue + further discussion can happen on 760
