### ISSUE TITLE
Default secp256k1 constructor creates new context, which is very slow

### ISSUE THREAD

**Issue by AdamISZ** [ethereum/pyethereum#782]
See  https://github.com/ludbb/secp256k1-py/issues/9 c.f. https://github.com/ethereum/pyethereum/blob/develop/ethereum/utils.py#L90 ; haven't looked at any other part of repo.

**Comment by ofek** [comment]
Hello there again! This will be fixed when https://github.com/ethereum/pyethereum/pull/777 gets merged.

**Comment by ofek** [comment]
@joeykrug @AdamISZ This was fixed in #777
