### ISSUE TITLE
Dependency problem in 2.0.5

### ISSUE THREAD

**Issue by berndbohmeier** [ethereum/pyethereum#806]
I get the following error message in a project using pyethereum as a dependency. With a freeze to version 2.0.4 it works fine. 

`Could not find a version that satisfies the requirement viper (from ethereum->-r requirements.txt (line 7)) (from versions: ) No matching distribution found for viper (from ethereum->-r requirements.txt (line 7))`

**Comment by fubuloubu** [comment]
I feel your pain, I want to use the `tester` module, but you can't do that from pypi directly. If you install `viper` first (https://github.com/ethereum/viper), then run `pip install ethereum==2.0.5` it will work.

#807 fixes this problem, however someone needs to re-upload ethereum 2.0.5 with that correction applied to pypi so the rest of us can use it no problem.

**Comment by changwu-tw** [comment]
@vbuterin Could you help to re-upload ethereum 2.0.5 to pypi? Thanks!

**Comment by fubuloubu** [comment]
@berndbohmeier You can close this, v2.1.0 was uploaded to pypi today!
