### ISSUE TITLE
Error in pip install with setuptools v38

### ISSUE THREAD

**Issue by bepetersn** [ethereum/pyethereum#832]
Here's the pip output:

```
pip install -U ethereum 
Collecting ethereum
  Using cached ethereum-2.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    error in ethereum setup command: 'tests_require' must be a string or list of strings containing valid project/version requirement specifiers; Unordered types are not allowed
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ug8q2t/ethereum/
```
It looks like I'm getting ethereum version 2.2.0.
```
python --version
Python 2.7.13
pip --version
pip 9.0.1 from /home/brian/.virtualenvs/eth/local/lib/python2.7/site-packages (python 2.7)
cat /etc/issue
Ubuntu 17.04 \n \l
```

It looks like your setup.py isn't working because `tests_require` is a set, but it seems like that's been like that for years. Not sure what the issue might be.

Edit: Ah, looks like your build is failing as well. 

> As of setuptools v38.0.0 it is no longer valid to use unordered
> sequences (sets or dicts) for install_requires or tests_require.
> 
> Reference:
> https://github.com/pypa/setuptools/blob/master/CHANGES.rst#v3800
>

**Comment by jeffnappi** [comment]
Also fixed in https://github.com/ethereum/pyethereum/pull/831

**Comment by joeykrug** [comment]
Fixed

**Comment by bepetersn** [comment]
Thanks! Sorry I didn't see.
