### ISSUE TITLE
Indentation error on ethereum/utils.py", line 30

### ISSUE THREAD

**Issue by sim-sliver** [ethereum/pyethereum#840]
```
    def __call__(self, *args):
        if args not in self.memo:
            self.memo[args] = self.fn(*args)   # <---------- THIS LINE
        return self.memo[args]
```

A mix of tab and space is used causing 
```TabError: inconsistent use of tabs and spaces in indentation```

**Comment by abhutra** [comment]
Very bad on the developer front allow such bugs to creep into production code.
:(
