### ISSUE TITLE
`pip install ethereum` references out-of-date upload 2.2.0 instead of "latest" 2.1.5

### ISSUE THREAD

**Issue by ghost** [ethereum/pyethereum#845]
Attempting to install Ethereum from `pip` (`pip 9.0.1 from /usr/lib/python3.6/site-packages (python 3.6)`) fails when a package uses `ethereum>=` in its requirements.txt. `pip` will then choose [ethereum-2.2.0](https://pypi.python.org/pypi/ethereum/2.2.0) from the package list as the latest version, instead of the true "latest" version [2.1.5](https://pypi.python.org/pypi/ethereum/2.1.5). The package 2.2.0 has a bad `tests_require` that causes packages to fail to install, using `set(` instead of `list(` at line 17.

This can be bypassed in the meantime by forcing the 2.1.5 package for some packages, such as `pip install ethereum==2.1.5 mythril` 

If 2.1.5 is actually the latest, 2.2.0 should be deleted from PyPI.

**Comment by joeykrug** [comment]
cc @vbuterin to remove 2.2.0, I think I can only upload new versions to pypi but can't delete

**Comment by joeykrug** [comment]
Went ahead and made a new minor release
