### ISSUE TITLE
Using contract functions

### ISSUE THREAD

**Issue by deveshaggrawal19** [ethereum/pyethereum#863]
I am trying to transfer some erc20 tokens using 

transaction = transactions.Transaction(nonce, gas_price, gas, to, value, data).sign(private_key)

but I cannot understand how to find the data needed to transfer the token. Can somebody guide me.

**Comment by aaronluoq** [comment]
you can use web3.py get nonce 
```
eth.getTransactionCount(address)
```

**Comment by deveshaggrawal19** [comment]
contract data for transfers. That is what I was looking for. I have resolved the issue. Thanks, mate.
