### ISSUE TITLE
An update in rlp break pyethereum imports

### ISSUE THREAD

**Issue by dragos-vlad** [ethereum/pyethereum#870]
Hello, 

There was an update in rlp that breaks the functionality of pyethereum. Bellow I have attached the traceback:

```
     from ethereum.utils import check_checksum
   File "/usr/local/lib/python3.6/site-packages/ethereum/__init__.py", line 11, in <module>
     from . import slogging  # noqa
   File "/usr/local/lib/python3.6/site-packages/ethereum/slogging.py", line 6, in <module>
     from ethereum.utils import bcolors, is_numeric
   File "/usr/local/lib/python3.6/site-packages/ethereum/utils.py", line 13, in <module>
     from rlp.utils import decode_hex, encode_hex, ascii_chr, str_to_bytes
 ImportError: cannot import name 'decode_hex'
```

I have also created an issue on the rlp repo: 
ethereum/pyrlp#87

**Comment by der-daniel** [comment]
Same here.

**Comment by purplebrabus** [comment]
It is because PyPI hasn't the last version, try to install it from this repository with git clone, i did it and now all works )

**Comment by Uxio0** [comment]
Hi, it's been already 2 months since that, would it be possible to release a minor version with this fix? Another libraries like pyevm depends on the new version of rlp, so I'm stuck in old versions because of pyethereum

**Comment by joeykrug** [comment]
Released a new version, should be fixed now
